export const HOME_GET_CLUSTER_ID_BEGIN = 'HOME_GET_CLUSTER_ID_BEGIN';
export const HOME_GET_CLUSTER_ID_SUCCESS = 'HOME_GET_CLUSTER_ID_SUCCESS';
export const HOME_GET_CLUSTER_ID_FAILURE = 'HOME_GET_CLUSTER_ID_FAILURE';
export const HOME_GET_CLUSTER_ID_DISMISS_ERROR = 'HOME_GET_CLUSTER_ID_DISMISS_ERROR';
